spring:
  application:
    name: funding-request-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/funding_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true

server:
  port: ${PORT:8080}
