CREATE TABLE country_limits (
    country VARCHAR(32) PRIMARY KEY,
    max_amount NUMERIC(15, 2) NOT NULL,
    CONSTRAINT chk_country_limit_positive CHECK (max_amount > 0)
);

CREATE TABLE funding_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_name VARCHAR(200) NOT NULL,
    country VARCHAR(32) NOT NULL,
    requested_amount NUMERIC(15, 2) NOT NULL,
    organization_age_years INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    decision_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_funding_request_country FOREIGN KEY (country) REFERENCES country_limits(country),
    CONSTRAINT chk_requested_amount_positive CHECK (requested_amount > 0),
    CONSTRAINT chk_organization_age_non_negative CHECK (organization_age_years >= 0),
    CONSTRAINT chk_request_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_funding_requests_status ON funding_requests(status);

INSERT INTO country_limits (country, max_amount) VALUES
    ('KENYA', 100000.00),
    ('UGANDA', 80000.00),
    ('TANZANIA', 90000.00),
    ('RWANDA', 75000.00),
    ('ZAMBIA', 85000.00);
